services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "MySecurePass123!"
      MYSQL_DATABASE: "php-app-deploy"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "AppUserPass456!"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
